/*
 * Sticky Radio Player - Full Width Shoutcast and Icecast HTML5 Player - v1.4.1
 *
 * Copyright 2016-2018, LambertGroup
 *
 */

 (function(e){function I(a,c,f,d){e(a.thumbsHolder_Thumbs[a.current_img_no]).css({background:c.playlistRecordBgOnColor,"border-bottom-color":c.playlistRecordBottomBorderOnColor,color:c.playlistRecordTextOnColor});a.is_very_first||C(-1,a,c,f);var m;""!=a.playlist_arr[a.origID].radiostream&&(m=a.playlist_arr[a.origID].radiostream);return m}function K(a,c,f,d,m,g,l,t,k,q){clearInterval(a.radioReaderAjaxInterval);e.get(c.pathToAjaxFiles+"now_playing.php",{the_stream:a.playlist_arr[a.origID].radiostream,
 _:e.now()},function(e){a.playlist_arr[a.origID].title=e;D(a,c,f,d,m,g,l,t,k,q)});D(a,c,f,d,m,g,l,t,k,q);a.isFlashNeeded?""!=a.myFlashObject&&a.myFlashObject.myAS3function(I(a,c,f,d),c.initialVolume):(document.getElementById(a.audioID).src=I(a,c,f,d),document.getElementById(a.audioID).load(),c.autoPlay&&m.click());setTimeout(function(){a.radioReaderAjaxInterval=setInterval(function(){e.get(c.pathToAjaxFiles+"now_playing.php",{the_stream:a.playlist_arr[a.origID].radiostream,_:e.now()},function(e){a.playlist_arr[a.origID].title=
 e;D(a,c,f,d,m,g,l,t,k,q)})},1E3*c.nowPlayingInterval)},1E3*c.nowPlayingInterval)}function L(a,c,f,d,m,g,l,t,k,q){for(var p=!1,u=0;u<a.playlist_arr.length&&!p&&0<a.playlist_arr.length;)a.playlist_arr[u].associatedpageurl==a.cur_loc&&(p=!0,a.current_img_no=u,a.origID=e("div[rel='"+a.current_img_no+"']").attr("data-origID"),K(a,c,f,d,m,g,l,t,k,q),C(-1,a,c,f)),u++}function D(a,c,e,d,m,g,l,t,k,q){g.width(a.titleWidth);t.width(a.titleWidth);a.curSongText="";c.showTitle&&null!=a.playlist_arr[a.origID].title&&
 ""!=a.playlist_arr[a.origID].title&&(a.curSongText+="<b>"+c.translateSongTitle+"</b>"+a.playlist_arr[a.origID].title);c.showRadioStation&&null!=a.playlist_arr[a.origID].station&&""!=a.playlist_arr[a.origID].station&&t.html("<b>"+c.translateRadioStation+"</b>"+a.playlist_arr[a.origID].station);e=a.playlist_arr[a.origID].title.split("-");var f=c.noImageAvailable;e[0]=e[0].trim();c.grabLastFmPhoto?a.lastfm.artist.getInfo({artist:e[0]},{success:function(a){""!=a.artist.image[3]["#text"].trim()&&(f=a.artist.image[3]["#text"]);
 q.css({background:"url("+f+") #000000","background-repeat":"no-repeat","background-position":"center center","background-size":"cover","border-width":c.imageBorderWidth+"px","border-color":c.imageBorderColor})},error:function(a,d){q.css({background:"url("+f+") #000000","background-repeat":"no-repeat","background-position":"center center","background-size":"cover","border-width":c.imageBorderWidth+"px","border-color":c.imageBorderColor})}}):q.css({background:"url("+f+") #000000","background-repeat":"no-repeat",
 "background-position":"center center","background-size":"cover","border-width":c.imageBorderWidth+"px","border-color":c.imageBorderColor});a.curSongText&&a.prevSongTitle!=a.playlist_arr[a.origID].title&&(l.css({width:"auto"}),a.isStationTitleInsideScrolling=!1,a.stationTitleInsideWait=0,l.stop(),l.css({"margin-left":0}),l.html(a.curSongText),clearInterval(a.timeupdateInterval),l.width()>a.titleWidth?a.timeupdateInterval=setInterval(function(){!a.isStationTitleInsideScrolling&&5<=a.stationTitleInsideWait&&
 l.width()>a.titleWidth?(a.isStationTitleInsideScrolling=!0,a.stationTitleInsideWait=0,l.html(a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "),l.css({"margin-left":0}),l.stop().animate({"margin-left":c.playerWidth-l.width()+"px"},parseInt(1E4*(l.width()-c.playerWidth)/150,10),"linear",function(){a.isStationTitleInsideScrolling=!1})):!a.isStationTitleInsideScrolling&&l.width()>a.titleWidth&&a.stationTitleInsideWait++},300):l.css({width:"100%"}),
 a.prevSongTitle=a.playlist_arr[a.origID].title)}function C(a,c,f,d){if(c.selectedCateg_total_images>f.numberOfThumbsPerScreen){var m=(c.thumbsHolder_ThumbHeight+1)*(c.selectedCateg_total_images-f.numberOfThumbsPerScreen),g=0;d.stop(!0,!0);e("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){a.preventDefault()});-1==a||c.isCarouselScrolling?!c.isCarouselScrolling&&c.selectedCateg_total_images>f.numberOfThumbsPerScreen&&(c.isCarouselScrolling=!0,g=-1*parseInt((c.thumbsHolder_ThumbHeight+
 1)*c.current_img_no,10),Math.abs(g)>m&&(g=-1*m),c.selectedCateg_total_images>f.numberOfThumbsPerScreen&&f.showPlaylist&&c.audio5_html5_sliderVertical.slider("value",100+parseInt(100*g/m)),d.animate({top:g+"px"},500,"easeOutCubic",function(){c.isCarouselScrolling=!1;e("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){})})):(c.isCarouselScrolling=!0,g=2>=a?-1*m:parseInt(m*(a-100)/100,10),0<g&&(g=0),d.animate({top:g+"px"},600,"easeOutQuad",function(){c.isCarouselScrolling=
 !1;e("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){})}))}}function R(a,c,f,d,m,g,l,t,k,q,p,u,r,v,w,z){d.stop(!0,!0);a.isCarouselScrolling=!1;d.stop().animate({left:-1*g.width()+"px"},100,"easeOutQuad",function(){d.html("");for(var n=0;n<a.category_arr.length;n++)a.thumbsHolder_Thumb=e('<div class="thumbsHolder_ThumbOFF" rel="'+n+'"><div class="padding">'+a.category_arr[n]+"</div></div>"),d.append(a.thumbsHolder_Thumb),a.thumbsHolder_Thumb.css({top:(a.thumbsHolder_Thumb.height()+
 1)*n+"px",background:c.categoryRecordBgOffColor,"border-bottom-color":c.categoryRecordBottomBorderOffColor,color:c.categoryRecordTextOffColor}),a.category_arr[n]==a.selectedCateg&&(a.current_img_no=n,a.thumbsHolder_Thumb.css({background:c.categoryRecordBgOnColor,"border-bottom-color":c.categoryRecordBottomBorderOnColor,color:c.categoryRecordTextOnColor}));a.selectedCateg_total_images=a.numberOfCategories;a.categsAreListed=!0;n=0;c.showCategories&&(n+=c.selectedCategMarginBottom);c.showSearchArea&&
 (n+=c.selectedCategMarginBottom);m.height(2*c.playlistPadding+(a.thumbsHolder_Thumb.height()+1)*c.numberOfThumbsPerScreen+l.height()+k.height()+n);g.height((a.thumbsHolder_Thumb.height()+1)*c.numberOfThumbsPerScreen);q.css({padding:c.playlistPadding+"px"});a.thumbsHolder_Thumbs=e(".thumbsHolder_ThumbOFF",f);if(a.numberOfCategories>c.numberOfThumbsPerScreen&&c.showPlaylist){c.isPlaylistSliderInitialized&&a.audio5_html5_sliderVertical.slider("destroy");a.audio5_html5_sliderVertical.slider({orientation:"vertical",
 range:"min",min:1,max:100,step:1,value:100,slide:function(e,f){C(f.value,a,c,d)}});c.isPlaylistSliderInitialized=!0;var h=0;c.showSearchArea&&(h+=c.selectedCategMarginBottom);a.audio5_html5_sliderVertical.css({display:"inline",position:"absolute",height:m.height()-16-l.height()-n-k.height()-2*c.playlistPadding+"px",left:f.width()+2*c.playerPadding-a.audio5_html5_sliderVertical.width()-c.playlistPadding+"px",bottom:a.audioPlayerHeight+c.playlistTopPos+c.playlistPadding+k.height()+h+16+"px"});c.showPlaylistOnInit||
 a.audio5_html5_sliderVertical.css({opacity:0,display:"none"});c.showPlaylistOnInit=!0;e(".thumbsHolder_ThumbOFF",f).css({width:f.width()+2*c.playerPadding-a.audio5_html5_sliderVertical.width()-2*c.playlistPadding-3+"px"})}else c.isPlaylistSliderInitialized&&(a.audio5_html5_sliderVertical.slider("destroy"),c.isPlaylistSliderInitialized=!1),e(".thumbsHolder_ThumbOFF",f).css({width:f.width()+2*c.playerPadding-2*c.playlistPadding+"px"});a.thumbsHolder_Thumbs.click(function(){var h=e(this).attr("rel");
 a.selectedCateg=a.category_arr[h];t.html(a.selectedCateg);N(a,c,f,d,m,g,l,k,q,p,u,r,v,w,z)});a.thumbsHolder_Thumbs.mouseover(function(){e(this).css({background:c.categoryRecordBgOnColor,"border-bottom-color":c.categoryRecordBottomBorderOnColor,color:c.categoryRecordTextOnColor})});a.thumbsHolder_Thumbs.mouseout(function(){var d=e(this),f=d.attr("rel");a.current_img_no!=f&&d.css({background:c.categoryRecordBgOffColor,"border-bottom-color":c.categoryRecordBottomBorderOffColor,color:c.categoryRecordTextOffColor})});
 g.mousewheel(function(e,f,b,k){e.preventDefault();e=a.audio5_html5_sliderVertical.slider("value");if(1<parseInt(e)&&-1==parseInt(f)||100>parseInt(e)&&1==parseInt(f))e+=f,a.audio5_html5_sliderVertical.slider("value",e),C(e,a,c,d)});d.css({top:"0px"});d.stop().animate({left:"0px"},400,"easeOutQuad",function(){})})}function N(a,c,f,d,m,g,l,t,k,q,p,u,r,v,w){d.stop(!0,!0);a.isCarouselScrolling=!1;var z="",n=!1,h=500;a.is_very_first&&(h=1);""!=a.search_val&&(h=1);d.stop().animate({left:-1*g.width()+"px"},
 h,"easeOutQuad",function(){d.html("");for(var h=a.selectedCateg_total_images=0;h<a.playlist_arr.length;h++)n=!1,""!=a.search_val?(z=a.playlist_arr[h].station.toLowerCase(),-1!=z.indexOf(a.search_val)&&(n=!0)):-1!=a.playlist_arr[h].category.indexOf(a.selectedCateg+";")&&(n=!0),n&&(a.selectedCateg_total_images++,a.thumbsHolder_Thumb=e('<div class="thumbsHolder_ThumbOFF" rel="'+(a.selectedCateg_total_images-1)+'" data-origID="'+h+'"><div class="padding">'+(c.showPlaylistNumber?a.selectedCateg_total_images+
 ". ":"")+a.playlist_arr[h].station+"</div></div>"),d.append(a.thumbsHolder_Thumb),0==a.thumbsHolder_ThumbHeight&&(a.thumbsHolder_ThumbHeight=a.thumbsHolder_Thumb.height()),a.thumbsHolder_Thumb.css({top:(a.thumbsHolder_ThumbHeight+1)*a.selectedCateg_total_images+"px",background:c.playlistRecordBgOffColor,"border-bottom-color":c.playlistRecordBottomBorderOffColor,color:c.playlistRecordTextOffColor}),a.current_img_no=0,a.origID==e("div[rel='"+(a.selectedCateg_total_images-1)+"']").attr("data-origID")&&
 a.thumbsHolder_Thumb.css({background:c.playlistRecordBgOnColor,"border-bottom-color":c.playlistRecordBottomBorderOnColor,color:c.playlistRecordTextOnColor}));a.categsAreListed=!1;h=0;c.showCategories&&(h+=c.selectedCategMarginBottom);c.showSearchArea&&(h+=c.selectedCategMarginBottom);m.height(2*c.playlistPadding+(a.thumbsHolder_ThumbHeight+1)*c.numberOfThumbsPerScreen+l.height()+t.height()+h);g.height((a.thumbsHolder_ThumbHeight+1)*c.numberOfThumbsPerScreen);k.css({padding:c.playlistPadding+"px"});
 a.thumbsHolder_Thumbs=e(".thumbsHolder_ThumbOFF",f);if(a.selectedCateg_total_images>c.numberOfThumbsPerScreen&&c.showPlaylist){c.isPlaylistSliderInitialized&&a.audio5_html5_sliderVertical.slider("destroy");a.audio5_html5_sliderVertical.slider({orientation:"vertical",range:"min",min:1,max:100,step:1,value:100,slide:function(b,e){C(e.value,a,c,d)}});c.isPlaylistSliderInitialized=!0;var A=0;c.showSearchArea&&(A+=c.selectedCategMarginBottom);a.audio5_html5_sliderVertical.css({display:"inline",position:"absolute",
 height:m.height()-16-l.height()-h-t.height()-2*c.playlistPadding+"px",left:f.width()+2*c.playerPadding-a.audio5_html5_sliderVertical.width()-c.playlistPadding+"px",bottom:a.audioPlayerHeight+c.playlistTopPos+c.playlistPadding+t.height()+A+16+"px"});c.showPlaylistOnInit||a.audio5_html5_sliderVertical.css({opacity:0,display:"none"});c.showPlaylistOnInit=!0;e(".thumbsHolder_ThumbOFF",f).css({width:f.width()+2*c.playerPadding-a.audio5_html5_sliderVertical.width()-2*c.playlistPadding-3+"px"})}else c.isPlaylistSliderInitialized&&
 (a.audio5_html5_sliderVertical.slider("destroy"),c.isPlaylistSliderInitialized=!1),e(".thumbsHolder_ThumbOFF",f).css({width:f.width()+2*c.playerPadding-2*c.playlistPadding+"px"});a.thumbsHolder_Thumbs.click(function(){c.autoPlay=!0;var b=e(this).attr("rel");a.thumbsHolder_Thumbs.css({background:c.playlistRecordBgOffColor,"border-bottom-color":c.playlistRecordBottomBorderOffColor,color:c.playlistRecordTextOffColor});a.current_img_no=b;a.origID=e("div[rel='"+a.current_img_no+"']").attr("data-origID");
 q.addClass("AudioPause");K(a,c,d,f,q,p,u,r,v,w);C(-1,a,c,d)});a.thumbsHolder_Thumbs.mouseover(function(){e(this).css({background:c.playlistRecordBgOnColor,"border-bottom-color":c.playlistRecordBottomBorderOnColor,color:c.playlistRecordTextOnColor})});a.thumbsHolder_Thumbs.mouseout(function(){var b=e(this),d=b.attr("rel");a.origID!=e("div[rel='"+d+"']").attr("data-origID")&&b.css({background:c.playlistRecordBgOffColor,"border-bottom-color":c.playlistRecordBottomBorderOffColor,color:c.playlistRecordTextOffColor})});
 g.mousewheel(function(b,e,f,h){b.preventDefault();b=a.audio5_html5_sliderVertical.slider("value");if(1<parseInt(b)&&-1==parseInt(e)||100>parseInt(b)&&1==parseInt(e))b+=e,a.audio5_html5_sliderVertical.slider("value",b),C(b,a,c,d)});d.css({top:"0px"});d.stop().animate({left:"0px"},400,"easeOutQuad",function(){});a.cur_loc=window.location.href;L(a,c,d,f,q,p,u,r,v,w);a.cur_intv=setInterval(function(){a.cur_loc!=window.location.href&&0<a.playlist_arr.length&&(a.cur_loc=window.location.href,L(a,c,d,f,q,
 p,u,r,v,w))},5E3)})}function P(a,c,f){"next"==f?a.current_img_no==a.selectedCateg_total_images-1?a.current_img_no=0:a.current_img_no++:0>a.current_img_no-1?a.current_img_no=a.selectedCateg_total_images-1:a.current_img_no--;a.origID=e("div[rel='"+a.current_img_no+"']").attr("data-origID")}function S(){e("audio").each(function(){e(".AudioPlay").removeClass("AudioPause");e(this)[0].pause()})}function Q(){var a=-1;if("Microsoft Internet Explorer"==navigator.appName){var c=navigator.userAgent,e=/MSIE ([0-9]{1,}[.0-9]{0,})/;
 null!=e.exec(c)&&(a=parseFloat(RegExp.$1))}else"Netscape"==navigator.appName&&(c=navigator.userAgent,e=/Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/,null!=e.exec(c)&&(a=parseFloat(RegExp.$1)));return parseInt(a,10)}function T(a){var c=!1;document.getElementById(a.audioID).canPlayType&&"no"!=document.getElementById(a.audioID).canPlayType("audio/mpeg")&&""!=document.getElementById(a.audioID).canPlayType("audio/mpeg")||(c=!0);return c}var A=navigator.userAgent.toLowerCase();e.fn.audio5_html5=function(a){a=e.extend({},
 e.fn.audio5_html5.defaults,a);Q();return this.each(function(){var c=e(this),f=e('<div class="FrameBehindPlayerText"></div><div class="FrameBehindPlayer"></div> <div class="headphone"></div> <div class="ximage"></div> <div class="AudioControls"> <a class="AudioFacebook" title="Facebook"></a><a class="AudioTwitter" title="Twitter"></a><a class="AudioPlay" title="Play/Pause"></a><a class="AudioPrev" title="Previous"></a><a class="AudioNext" title="Next"></a><a class="AudioShowHidePlaylist" title="Show/Hide Playlist"></a><a class="VolumeButton" title="Mute/Unmute"></a><div class="VolumeSlider"></div>   </div>   <div class="songTitle"><div class="songTitleInside"></div></div>  <div class="radioStation"></div>     <div class="thumbsHolderWrapper"><div class="playlistPadding"><div class="selectedCategDiv"><div class="innerSelectedCategDiv">reading the categories...</div></div> <div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div><div class="searchDiv"><input class="search_term" type="text" value="search..." /></div></div></div>  <div class="slider-vertical"></div>'),
 d=c.parent(".audio5_html5");d.addClass(a.skin);d.append(f);var m=e(".FrameBehindPlayerText",d),g=e(".FrameBehindPlayer",d);e(".AudioControls",d);var l=e(".AudioFacebook",d),t=e(".AudioTwitter",d),k=e(".AudioPlay",d),q=e(".AudioPrev",d),p=e(".AudioNext",d),u=e(".AudioShowHidePlaylist",d),r=e(".VolumeButton",d),v=e(".VolumeSlider",d),w=e(".songTitle",d),z=e(".songTitleInside",d),n=e(".radioStation",d),h=e(".ximage",d),J=e(".headphone",d),D=Q();if(-1!=A.indexOf("ipad")||-1!=A.indexOf("iphone")||-1!=
 A.indexOf("ipod")||-1!=A.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android"))a.autoHidePlayButton=!1,k.css("display","block"),a.autoPlay=!1;d.css({background:"transparent",padding:a.playerPadding+"px"});g.css({background:a.frameBehindPlayerColor});m.css({background:a.beneathTitleBackgroundColor_VisiblePlaylist,opacity:a.beneathTitleBackgroundOpacity_VisiblePlaylist/100,"border-bottom":a.beneathTitleBackgroundBorderWidth+"px solid "+a.beneathTitleBackgroundBorderColor});jQuery(".audio5_html5_arrow_down").css({"border-top-color":a.minButtonColor});
 jQuery(".audio5_html5_min").click(function(){jQuery(this).hasClass("audio5_html5_arrow_down")?(jQuery(this).removeClass("audio5_html5_arrow_down"),jQuery(this).addClass("audio5_html5_arrow_up"),jQuery(".audio5_html5_arrow_up").css({"border-bottom-color":a.minButtonColor})):(jQuery(this).removeClass("audio5_html5_arrow_up"),jQuery(this).addClass("audio5_html5_arrow_down"));d.slideToggle(400,function(){})});var b={current_img_no:0,origID:0,is_very_first:!0,total_images:0,selectedCateg_total_images:0,
 numberOfCategories:0,is_changeSrc:!1,timeupdateInterval:"",totalTime:"",playlist_arr:"",isCarouselScrolling:!1,isStationTitleInsideScrolling:!1,curSongText:"",prevSongTitle:"",stationTitleInsideWait:0,audioPlayerWidth:0,audioPlayerHeight:0,category_arr:"",selectedCateg:"",categsAreListed:!1,thumbsHolder_Thumb:e('<div class="thumbsHolder_ThumbOFF" rel="0"><div class="padding">test</div></div>'),thumbsHolder_ThumbHeight:0,thumbsHolder_Thumbs:"",search_val:"",constantDistance:5,playerTopMargin:23,titleWidth:0,
 radioStationTopPos:0,radioStationLeftPos:0,titleTopPos:0,titleLeftPos:0,frameBehindPlayerTopPos:0,frameBehindPlayerLeftPos:0,imageTopPos:0,imageLeftPos:0,playTopPos:0,playLeftPos:0,previousTopPos:0,previousLeftPos:0,nextTopPos:0,nextLeftPos:0,headphoneTopPos:0,headphoneLeftPos:0,volumeTopPos:0,volumeLeftPos:0,volumesliderTopPos:0,volumesliderLeftPos:0,showhideplaylistTopPos:0,showhideplaylistLeftPos:0,smallButtonDistance:0,facebookTopPos:0,facebookLeftPos:0,twitterTopPos:0,twitterLeftPos:0,numberOfButtonsRightSide:3,
 origParentFloat:"",origParentPaddingTop:"",origParentPaddingRight:"",origParentPaddingBottom:"",origParentPaddingLeft:"",windowWidth:0,audioID:"",audioObj:"",radioReaderAjaxInterval:"",totalRadioStationsNo:0,ajaxReturnedRadioStationsNo:0,lastfm:"",isFlashNeeded:!0,myFlashObject:"",rndNum:0,prevVolumeVal:1,cur_loc:"",cur_intv:""};b.audioID=c.attr("id");b.isFlashNeeded=T(b);-1!=D&&(b.isFlashNeeded=!0);a.showFacebookBut||--b.numberOfButtonsRightSide;a.showTwitterBut||--b.numberOfButtonsRightSide;a.showPlaylistBut||
 --b.numberOfButtonsRightSide;a.showPlaylistBut||u.css({display:"none",padding:0,margin:0});a.showHeadphone||(b.playerTopMargin=0);d.width(a.playerWidth);a.origWidth=a.playerWidth;g.css({top:parseInt((h.height()+2*a.imageBorderWidth-g.height())/2,10)+b.playerTopMargin+"px",left:"0px"});b.frameBehindPlayerTopPos=parseInt(g.css("top").substring(0,g.css("top").length-2),10);b.frameBehindPlayerLeftPos=parseInt(g.css("left").substring(0,g.css("left").length-2),10);m.css({top:b.frameBehindPlayerTopPos+g.height()+
 "px",left:"0px"});h.css({top:b.playerTopMargin+"px",left:parseInt((d.width()-(h.width()+2*a.imageBorderWidth))/2,10)+"px"});b.imageTopPos=parseInt(h.css("top").substring(0,h.css("top").length-2),10);b.imageLeftPos=parseInt(h.css("left").substring(0,h.css("left").length-2),10);a.autoHidePlayButton&&(e("*").on("click",function(){k.css({display:"none"})}),h.mouseover(function(){k.css({display:"block"})}),h.mouseout(function(){k.css({display:"none"})}),k.mouseover(function(){k.css({display:"block"})}));
 h.click(function(){k.click();k.css({display:"block"})});b.playTopPos=b.frameBehindPlayerTopPos+parseInt((g.height()-k.height())/2,10);b.playLeftPos=parseInt((g.width()-k.width())/2,10);k.css({top:b.playTopPos+"px",left:b.playLeftPos+"px"});a.autoHidePlayButton&&setTimeout(function(){k.fadeOut(1500,function(){})},2E3);a.showNextPrevBut||(q.css({display:"none",width:0,padding:0,margin:0}),p.css({display:"none",width:0,padding:0,margin:0}));b.previousTopPos=b.playTopPos+parseInt((k.height()-q.height())/
 2,10);b.previousLeftPos=b.imageLeftPos-q.width()-a.nextPrevAdditionalPadding;q.css({top:b.previousTopPos+"px",left:b.previousLeftPos+"px"});b.nextTopPos=b.previousTopPos;b.nextLeftPos=b.imageLeftPos+(h.width()+2*a.imageBorderWidth)+a.nextPrevAdditionalPadding;p.css({top:b.nextTopPos+"px",left:b.nextLeftPos+"px"});a.showHeadphone?(b.headphoneTopPos=0,b.headphoneLeftPos=parseInt(b.imageLeftPos+(h.width()+2*a.imageBorderWidth-J.width())/2,10),J.css({left:b.headphoneLeftPos+"px",top:b.headphoneTopPos+
 "px"})):J.css({display:"none"});a.showVolume?(b.volumeTopPos=b.nextTopPos+Math.floor((p.height()-r.height())/2),b.volumeLeftPos=parseInt((b.previousLeftPos-(r.width()+v.width()+b.constantDistance))/2,10),r.css({top:b.volumeTopPos+"px",left:b.volumeLeftPos+"px"}),b.volumesliderTopPos=b.volumeTopPos+Math.floor((r.height()-v.height())/2),b.volumesliderLeftPos=b.volumeLeftPos+r.width()+b.constantDistance,v.css({top:b.volumesliderTopPos+"px",left:b.volumesliderLeftPos+"px"})):(r.css({display:"none",width:0,
 padding:0,margin:0}),v.css({display:"none",width:0,padding:0,margin:0}));b.audioPlayerHeight=h.height()+2*a.imageBorderWidth+b.constantDistance+n.height()+b.constantDistance+w.height()+2*b.constantDistance+b.playerTopMargin;a.showRadioStation||a.showTitle?a.showTitle||(b.audioPlayerHeight-=21):b.audioPlayerHeight-=42;d.height(b.audioPlayerHeight);b.smallButtonDistance=parseInt((a.playerWidth-b.nextLeftPos-p.width()-b.numberOfButtonsRightSide*u.width())/(b.numberOfButtonsRightSide+1),10);b.facebookTopPos=
 b.nextTopPos+Math.floor((p.height()-l.height())/2);b.facebookLeftPos=b.nextLeftPos+p.width()+b.smallButtonDistance;l.css({top:b.facebookTopPos+"px",left:b.facebookLeftPos+"px"});a.showFacebookBut?(window.fbAsyncInit=function(){FB.init({appId:a.facebookAppID,version:"v2.8",status:!0,cookie:!0,xfbml:!0})},function(a,b,c){var d=a.getElementsByTagName(b)[0];a.getElementById(c)||(a=a.createElement(b),a.id=c,a.src="//connect.facebook.com/en_US/sdk.js",d.parentNode.insertBefore(a,d))}(document,"script",
 "facebook-jssdk")):(l.css({display:"none",width:0,padding:0,margin:0}),b.facebookLeftPos=b.nextLeftPos+p.width());l.click(function(){FB.ui({method:"feed",name:a.facebookShareTitle,caption:b.playlist_arr[b.origID].station,description:a.facebookShareDescription,link:document.URL},function(a){})});b.twitterTopPos=b.nextTopPos+Math.floor((p.height()-l.height())/2);b.twitterLeftPos=b.facebookLeftPos+l.width()+b.smallButtonDistance;t.css({top:b.twitterTopPos+"px",left:b.twitterLeftPos+"px"});a.showTwitterBut||
 (t.css({display:"none",width:0,padding:0,margin:0}),b.twitterLeftPos=b.facebookLeftPos+l.width());t.click(function(){var a=b.playlist_arr[b.origID].station.replace("%","percent");a=a.replace("&"," and ");window.open("https://twitter.com/intent/tweet?url="+document.URL+"&text="+a,"Twitter","status = 1, left = 430, top = 270, height = 550, width = 420, resizable = 0")});b.showhideplaylistTopPos=b.nextTopPos+Math.floor((p.height()-u.height())/2);b.showhideplaylistLeftPos=b.volumeLeftPos-b.smallButtonDistance;
 u.css({top:b.showhideplaylistTopPos+"px",left:b.showhideplaylistLeftPos+"px"});w.css({color:a.songTitleColor});n.css({color:a.radioStationColor});b.titleWidth=a.playerWidth-2*a.playlistPadding;b.radioStationTopPos=b.imageTopPos+(h.width()+2*a.imageBorderWidth)+2*b.constantDistance;b.radioStationLeftPos=a.playlistPadding;b.titleTopPos=b.imageTopPos+(h.width()+2*a.imageBorderWidth)+2*b.constantDistance+n.height()+b.constantDistance;b.titleLeftPos=a.playlistPadding;n.css({top:b.radioStationTopPos+"px",
 left:b.radioStationLeftPos+"px"});w.css({top:b.titleTopPos+"px",left:b.titleLeftPos+"px"});m.css({top:b.frameBehindPlayerTopPos+g.height()+"px",left:"0px",height:parseInt(d.height()/2,10)+g.height()+"px"});var x=e(".thumbsHolderWrapper",d),M=e(".playlistPadding",d),E=e(".thumbsHolderVisibleWrapper",d),y=e(".thumbsHolder",d);b.audio5_html5_sliderVertical=e(".slider-vertical",d);var B=e(".selectedCategDiv",d),F=e(".innerSelectedCategDiv",d),G=e(".searchDiv",d),H=e(".search_term",d);M.css({padding:a.playlistPadding+
 "px"});E.append('<div class="readingData">'+a.translateReadingData+"</div>");a.showPlaylist||x.css({opacity:0});a.showPlaylistOnInit||(x.css({opacity:0,visibility:"hidden","margin-top":"-20px"}),m.css({background:a.beneathTitleBackgroundColor_HiddenPlaylist,opacity:a.beneathTitleBackgroundOpacity_HiddenPlaylist/100,"border-bottom":a.beneathTitleBackgroundBorderWidth+"px solid "+a.beneathTitleBackgroundBorderColor}));B.css({"background-color":a.selectedCategBg,"background-position":"10px 50%","margin-bottom":a.selectedCategMarginBottom+
 "px"});F.css({color:a.selectedCategOffColor,"background-position":a.playerWidth-2*a.playlistPadding-20+"px 50%"});a.showCategories||B.css({display:"none",width:0,height:0,padding:0,margin:0});G.css({"background-color":a.searchAreaBg,"margin-top":a.selectedCategMarginBottom+"px"});H.val(a.searchInputText);H.css({width:parseInt(a.playerWidth-2*a.playlistPadding-37,10)+"px","background-color":a.searchInputBg,"border-color":a.searchInputBorderColor,color:a.searchInputTextColor});a.showSearchArea||G.css({display:"none",
 width:0,height:0,padding:0,margin:0});x.css({width:d.width()+2*a.playerPadding+"px",bottom:-1*b.audioPlayerHeight+"px",left:"0px",background:a.playlistBgColor});E.width(d.width());b.playlist_arr=[];b.category_arr=[];e(".xaudioplaylist",d).children().each(function(){currentElement=e(this);b.total_images++;b.playlist_arr[b.total_images-1]=[];b.playlist_arr[b.total_images-1].title="";b.playlist_arr[b.total_images-1].station="";b.playlist_arr[b.total_images-1].image="";b.playlist_arr[b.total_images-1].category=
 "";b.playlist_arr[b.total_images-1].radiostream="";b.playlist_arr[b.total_images-1].associatedpageurl="";null!=currentElement.find(".xtitle").html()&&(b.playlist_arr[b.total_images-1].title=currentElement.find(".xtitle").html());null!=currentElement.find(".xstation").html()&&(b.playlist_arr[b.total_images-1].station=currentElement.find(".xstation").html());null!=currentElement.find(".ximage").html()&&(b.playlist_arr[b.total_images-1].image=currentElement.find(".ximage").html());if(null!=currentElement.find(".xcategory").html()&&
 (b.playlist_arr[b.total_images-1].category=a.translateAllRadioStations+";"+currentElement.find(".xcategory").html()+";",!a.grabStreamnameAndGenre)){var f=[];f=b.playlist_arr[b.total_images-1].category.split(";");for(var g=0;g<f.length;g++)f[g]=f[g].trim(),-1===b.category_arr.indexOf(f[g])&&""!=f[g]&&b.category_arr.push(f[g])}null!=currentElement.find(".xassociatedpageurl").html()&&(b.playlist_arr[b.total_images-1].associatedpageurl=currentElement.find(".xassociatedpageurl").html());null!=currentElement.find(".xradiostream").html()&&
 (b.playlist_arr[b.total_images-1].radiostream=currentElement.find(".xradiostream").html(),-1==b.playlist_arr[b.total_images-1].radiostream.indexOf("/",9)&&(b.playlist_arr[b.total_images-1].radiostream+="/;"),"/"==b.playlist_arr[b.total_images-1].radiostream.charAt(b.playlist_arr[b.total_images-1].radiostream.length-1)&&(b.playlist_arr[b.total_images-1].radiostream+=";"),b.totalRadioStationsNo++,a.grabStreamnameAndGenre&&e.get(a.pathToAjaxFiles+"streamandgenre.php",{the_stream:b.playlist_arr[b.total_images-
 1].radiostream,cur_i:b.total_images-1,translateAllRadioStations:a.translateAllRadioStations,_:e.now()},function(f){b.ajaxReturnedRadioStationsNo++;f=f.split("#----#");2<=f.length&&""==b.playlist_arr[f[0]].station&&(b.playlist_arr[f[0]].station=f[1]);3<=f.length&&""==b.playlist_arr[f[0]].category&&(b.playlist_arr[f[0]].category=f[2]+";");""==b.playlist_arr[f[0]].category&&(b.playlist_arr[f[0]].category=a.translateAllRadioStations);f=b.playlist_arr[f[0]].category.split(";");for(var g=0;g<f.length;g++)f[g]=
 f[g].trim(),-1===b.category_arr.indexOf(f[g])&&""!=f[g]&&b.category_arr.push(f[g]);b.ajaxReturnedRadioStationsNo==b.totalRadioStationsNo&&(b.numberOfCategories=b.category_arr.length,b.selectedCateg=a.firstCateg,b.category_arr.sort(),""==a.firstCateg&&-1===b.category_arr.indexOf(a.firstCateg)&&(b.selectedCateg=b.category_arr[0]),F.html(b.selectedCateg),e(".readingData").remove(),N(b,a,d,y,x,E,B,G,M,k,w,z,n,c,h))}))});a.grabStreamnameAndGenre||(b.numberOfCategories=b.category_arr.length,b.selectedCateg=
 a.firstCateg,b.category_arr.sort(),""==a.firstCateg&&-1===b.category_arr.indexOf(a.firstCateg)&&(b.selectedCateg=b.category_arr[0]),F.html(b.selectedCateg),e(".readingData").remove(),N(b,a,d,y,x,E,B,G,M,k,w,z,n,c,h));a.grabLastFmPhoto&&(f=new LastFMCache,b.lastfm=new LastFM({apiKey:a.lastFMApiKey,apiSecret:a.lastFMSecret,cache:f}));B.click(function(){b.search_val="";H.val(a.searchInputText);R(b,a,d,y,x,E,B,F,G,M,k,w,z,n,c,h)});B.mouseover(function(){F.css({color:a.selectedCategOnColor})});B.mouseout(function(){F.css({color:a.selectedCategOffColor})});
 v.slider({value:a.initialVolume,step:.05,orientation:"horizontal",range:"min",max:1,animate:!0,slide:function(c,e){a.initialVolume=e.value;b.isFlashNeeded?b.myFlashObject.myAS3function(I(b,a,y,d),a.initialVolume):document.getElementById(b.audioID).volume=e.value},stop:function(a,b){}});document.getElementById(b.audioID).volume=a.initialVolume;v.css({background:a.volumeOffColor});e(".ui-slider-range",v).css({background:a.volumeOnColor});k.click(function(){var c=b.isFlashNeeded?!k.hasClass("AudioPause"):
 document.getElementById(b.audioID).paused;S();0==c?(b.isFlashNeeded?b.myFlashObject.myAS3function("_pause_radio_stream_",a.initialVolume):document.getElementById(b.audioID).pause(),k.removeClass("AudioPause")):(b.isFlashNeeded?b.myFlashObject.myAS3function("_play_radio_stream_",a.initialVolume):(document.getElementById(b.audioID).src=I(b,a,y,d),document.getElementById(b.audioID).load(),document.getElementById(b.audioID).play()),k.addClass("AudioPause"))});p.click(function(){!b.categsAreListed&&b.is_very_first&&
 (k.addClass("AudioPause"),a.autoPlay=!0,b.thumbsHolder_Thumbs.css({background:a.playlistRecordBgOffColor,"border-bottom-color":a.playlistRecordBottomBorderOffColor,color:a.playlistRecordTextOffColor}),P(b,a,"next"),K(b,a,y,d,k,w,z,n,c,h),C(-1,b,a,y))});q.click(function(){!b.categsAreListed&&b.is_very_first&&(k.addClass("AudioPause"),a.autoPlay=!0,b.thumbsHolder_Thumbs.css({background:a.playlistRecordBgOffColor,"border-bottom-color":a.playlistRecordBottomBorderOffColor,color:a.playlistRecordTextOffColor}),
 P(b,a,"previous"),K(b,a,y,d,k,w,z,n,c,h),C(-1,b,a,y))});u.click(function(){x.css({visibility:"visible"});if(0>x.css("bottom").substring(0,x.css("bottom").length-2)){var c=1,d="block";B.height();G.height();aux_bottom=b.audioPlayerHeight+a.playlistTopPos;x.css({display:d});m.css({background:a.beneathTitleBackgroundColor_VisiblePlaylist,opacity:a.beneathTitleBackgroundOpacity_VisiblePlaylist/100,"border-bottom":a.beneathTitleBackgroundBorderWidth+"px solid "+a.beneathTitleBackgroundBorderColor})}else c=
 0,d="none",aux_bottom=-1*b.audioPlayerHeight,b.selectedCateg_total_images>a.numberOfThumbsPerScreen&&b.audio5_html5_sliderVertical.css({opacity:0,display:"none"}),m.css({background:a.beneathTitleBackgroundColor_HiddenPlaylist,opacity:a.beneathTitleBackgroundOpacity_HiddenPlaylist/100,"border-bottom":a.beneathTitleBackgroundBorderWidth+"px solid "+a.beneathTitleBackgroundBorderColor});x.css({opacity:1,display:"block"});x.animate({opacity:c,bottom:aux_bottom+"px"},500,"swing",function(){x.css({display:d});
 b.selectedCateg_total_images>a.numberOfThumbsPerScreen&&b.audio5_html5_sliderVertical.css({opacity:1,display:d})})});r.click(function(){document.getElementById(b.audioID).muted?(document.getElementById(b.audioID).muted=!1,r.removeClass("VolumeButtonMuted"),b.isFlashNeeded&&(a.initialVolume=b.prevVolumeVal,b.myFlashObject.myAS3function(I(b,a,y,d),a.initialVolume))):(document.getElementById(b.audioID).muted=!0,r.addClass("VolumeButtonMuted"),b.isFlashNeeded&&(b.prevVolumeVal=a.initialVolume,a.initialVolume=
 0,b.myFlashObject.myAS3function(I(b,a,y,d),a.initialVolume)))});y.swipe({swipeStatus:function(c,d,f,g,h,k){"up"!=f&&"down"!=f||0==g||(currentScrollVal=b.audio5_html5_sliderVertical.slider("value"),currentScrollVal="up"==f?currentScrollVal-1.5:currentScrollVal+1.5,b.audio5_html5_sliderVertical.slider("value",currentScrollVal),e("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){a.preventDefault()}),C(currentScrollVal,b,a,y))},threshold:100,maxTimeThreshold:500,fingers:"all"});
 H.on("click",function(){e(this).val("")});H.on("input",function(){b.search_val=H.val().toLowerCase();N(b,a,d,y,x,E,B,G,M,k,w,z,n,c,h)});b.isFlashNeeded&&(b.rndNum=parseInt(998999*Math.random()+1E3),d.append("<div id='swfHolder"+b.rndNum+"'></div>"),swfobject.addDomLoadEvent(function(){b.myFlashObject=swfobject.createSWF({data:a.pathToAjaxFiles+"flash_player.swf",width:"0",height:"0"},{flashvars:"streamUrl="+b.playlist_arr[b.origID].radiostream+"&autoPlay="+a.autoPlay+"&initialVolume="+a.initialVolume},
 "swfHolder"+b.rndNum)}),a.autoPlay&&k.addClass("AudioPause"));K(b,a,y,d,k,w,z,n,c,h);-1==A.indexOf("ipad")&&-1==A.indexOf("iphone")&&-1==A.indexOf("ipod")&&-1==A.indexOf("webos")||k.removeClass("AudioPause");var L=function(){b.prevSongTitle="";""==b.origParentFloat&&(b.origParentFloat=d.parent().css("float"),b.origParentPaddingTop=d.parent().css("padding-top"),b.origParentPaddingRight=d.parent().css("padding-right"),b.origParentPaddingBottom=d.parent().css("padding-bottom"),b.origParentPaddingLeft=
 d.parent().css("padding-left"));a.playerWidth!=a.origWidth||a.playerWidth>e(window).width()?d.parent().css({"float":"none","padding-top":0,"padding-right":0,"padding-bottom":0,"padding-left":0}):d.parent().css({"float":b.origParentFloat,"padding-top":b.origParentPaddingTop,"padding-right":b.origParentPaddingRight,"padding-bottom":b.origParentPaddingBottom,"padding-left":b.origParentPaddingLeft});var c=d.parent().width(),f=b.numberOfButtonsRightSide;d.width()!=c&&(a.playerWidth=a.origWidth>c?c:a.origWidth,
 d.width()!=a.playerWidth&&(d.width(a.playerWidth),b.titleWidth=a.playerWidth-2*a.playlistPadding,w.width(b.titleWidth),n.width(b.titleWidth),h.css({top:b.playerTopMargin+"px",left:parseInt((d.width()-(h.width()+2*a.imageBorderWidth))/2,10)+"px"}),b.imageLeftPos=parseInt(h.css("left").substring(0,h.css("left").length-2),10),b.playTopPos=b.frameBehindPlayerTopPos+parseInt((g.height()-k.height())/2,10),b.playLeftPos=parseInt((g.width()-k.width())/2,10),k.css({top:b.playTopPos+"px",left:b.playLeftPos+
 "px"}),b.previousTopPos=b.playTopPos+parseInt((k.height()-q.height())/2,10),b.previousLeftPos=b.imageLeftPos-q.width()-a.nextPrevAdditionalPadding,q.css({top:b.previousTopPos+"px",left:b.previousLeftPos+"px"}),b.nextTopPos=b.previousTopPos,b.nextLeftPos=b.imageLeftPos+(h.width()+2*a.imageBorderWidth)+a.nextPrevAdditionalPadding,p.css({top:b.nextTopPos+"px",left:b.nextLeftPos+"px"}),a.showHeadphone?(b.headphoneTopPos=0,b.headphoneLeftPos=parseInt(b.imageLeftPos+(h.width()+2*a.imageBorderWidth-J.width())/
 2,10),J.css({left:b.headphoneLeftPos+"px",top:b.headphoneTopPos+"px"})):J.css({display:"none"}),b.volumeTopPos=b.nextTopPos+Math.floor((p.height()-r.height())/2),b.volumeLeftPos=parseInt((b.previousLeftPos-(r.width()+v.width()+b.constantDistance))/2,10),r.css({top:b.volumeTopPos+"px",left:b.volumeLeftPos+"px"}),b.volumesliderTopPos=b.volumeTopPos+Math.floor((r.height()-v.height())/2),b.volumesliderLeftPos=b.volumeLeftPos+r.width()+b.constantDistance,v.css({top:b.volumesliderTopPos+"px",left:b.volumesliderLeftPos+
 "px"}),355>a.playerWidth?a.showTwitterBut&&--f:f=b.numberOfButtonsRightSide,b.smallButtonDistance=parseInt((a.playerWidth-b.nextLeftPos-p.width()-f*u.width())/(f+1),10),b.facebookTopPos=b.nextTopPos+Math.floor((p.height()-l.height())/2),b.facebookLeftPos=b.nextLeftPos+p.width()+b.smallButtonDistance,l.css({top:b.facebookTopPos+"px",left:b.facebookLeftPos+"px"}),a.showFacebookBut||(l.css({display:"none",width:0,height:0,padding:0,margin:0}),b.facebookLeftPos=b.nextLeftPos+p.width()),!a.showTwitterBut||
 355>a.playerWidth?(t.css({display:"none"}),b.twitterLeftPos=b.facebookLeftPos+l.width()-6):(t.css({display:"block"}),b.twitterTopPos=b.nextTopPos+Math.floor((p.height()-l.height())/2),b.twitterLeftPos=b.facebookLeftPos+l.width()+b.smallButtonDistance,t.css({top:b.twitterTopPos+"px",left:b.twitterLeftPos+"px"})),b.showhideplaylistTopPos=b.nextTopPos+Math.floor((p.height()-u.height())/2),b.showhideplaylistLeftPos=b.volumeLeftPos-b.smallButtonDistance,u.css({top:b.showhideplaylistTopPos+"px",left:b.showhideplaylistLeftPos+
 "px"}),x.width(d.width()+2*a.playerPadding),E.width(d.width()),B.width(a.playerWidth-2*a.playlistPadding),F.css({"background-position":a.playerWidth-2*a.playlistPadding-20+"px 50%"}),b.selectedCateg_total_images>a.numberOfThumbsPerScreen&&a.showPlaylist?(b.audio5_html5_sliderVertical.css({left:d.width()+2*a.playerPadding-b.audio5_html5_sliderVertical.width()-a.playlistPadding+"px"}),e(".thumbsHolder_ThumbOFF",d).css({width:d.width()+2*a.playerPadding-b.audio5_html5_sliderVertical.width()-2*a.playlistPadding-
 3+"px"})):e(".thumbsHolder_ThumbOFF",d).css({width:d.width()+2*a.playerPadding-2*a.playlistPadding+"px"}),H.css({width:parseInt(a.playerWidth-2*a.playlistPadding-50,10)+"px"})),a.playerWidth<e(window).width()&&d.parent().css({"float":b.origParentFloat,"padding-top":b.origParentPaddingTop,"padding-right":b.origParentPaddingRight,"padding-bottom":b.origParentPaddingBottom,"padding-left":b.origParentPaddingLeft}));445>a.playerWidth?(v.css({display:"none"}),r.css({display:"none"}),u.css({left:b.smallButtonDistance+
 "px"})):(v.css({display:"block"}),r.css({display:"block"}))},O=!1;e(window).resize(function(){doResizeNow=!0;-1!=D&&9==D&&0==b.windowWidth&&(doResizeNow=!1);b.windowWidth==e(window).width()?(doResizeNow=!1,a.windowCurOrientation!=window.orientation&&-1!=navigator.userAgent.indexOf("Android")&&(a.windowCurOrientation=window.orientation,doResizeNow=!0)):b.windowWidth=e(window).width();a.responsive&&doResizeNow&&(!1!==O&&clearTimeout(O),O=setTimeout(function(){L()},300))});a.responsive&&L()})};e.fn.audio5_html5.defaults=
 {playerWidth:5E3,skin:"whiteControllers",initialVolume:.5,autoPlay:!0,loop:!0,playerPadding:0,playerBg:"#000000",volumeOffColor:"#454545",volumeOnColor:"#ffffff",timerColor:"#ffffff",songTitleColor:"#000000",radioStationColor:"#000000",frameBehindPlayerColor:"#000000",imageBorderWidth:4,imageBorderColor:"#000000",showFacebookBut:!0,facebookAppID:"499867206825745",facebookShareTitle:"Sticky Radio Player - Full Width Shoutcast and Icecast HTML5 Player",facebookShareDescription:"A top-notch responsive HTML5 Radio Player compatible with all major browsers and mobile devices.",
 showVolume:!0,showTwitterBut:!0,showRadioStation:!0,showTitle:!0,showPlaylistBut:!0,showPlaylist:!0,showPlaylistOnInit:!1,showNextPrevBut:!0,showHeadphone:!0,nextPrevAdditionalPadding:-5,autoHidePlayButton:!0,beneathTitleBackgroundColor_VisiblePlaylist:"#c55151",beneathTitleBackgroundOpacity_VisiblePlaylist:100,beneathTitleBackgroundColor_HiddenPlaylist:"#c55151",beneathTitleBackgroundOpacity_HiddenPlaylist:100,beneathTitleBackgroundBorderColor:"#000000",beneathTitleBackgroundBorderWidth:3,translateRadioStation:"Radio Station: ",
 translateSongTitle:"Now Playing: ",translateReadingData:"reading data...",translateAllRadioStations:"ALL RADIO STATIONS",playlistTopPos:5,playlistBgColor:"#c55151",playlistRecordBgOffColor:"#000000",playlistRecordBgOnColor:"#000000",playlistRecordBottomBorderOffColor:"#333333",playlistRecordBottomBorderOnColor:"#4d4d4d",playlistRecordTextOffColor:"#777777",playlistRecordTextOnColor:"#00b4f9",categoryRecordBgOffColor:"#000000",categoryRecordBgOnColor:"#252525",categoryRecordBottomBorderOffColor:"#2f2f2f",
 categoryRecordBottomBorderOnColor:"#2f2f2f",categoryRecordTextOffColor:"#777777",categoryRecordTextOnColor:"#00b4f9",numberOfThumbsPerScreen:7,playlistPadding:18,showCategories:!0,firstCateg:"ALL RADIO STATIONS",selectedCategBg:"#000000",selectedCategOffColor:"#FFFFFF",selectedCategOnColor:"#00b4f9",selectedCategMarginBottom:12,showSearchArea:!0,searchAreaBg:"#000000",searchInputText:" search...",searchInputBg:"#ffffff",searchInputBorderColor:"#333333",searchInputTextColor:"#333333",minButtonColor:"#FFFFFF",
 responsive:!0,showPlaylistNumber:!0,nowPlayingInterval:35,grabLastFmPhoto:!0,grabStreamnameAndGenre:!0,pathToAjaxFiles:"",noImageAvailable:"noimageavailable.jpg",lastFMApiKey:"6d38069793ab51b1f7f010d8f4d77000",lastFMSecret:"5f1bb73c21038e2ed7125c9ed6205cb8",origWidth:0,isSliderInitialized:!1,isProgressInitialized:!1,isPlaylistSliderInitialized:!1}})(jQuery);
